### PR TITLE
add pullapprove yml file

### PR DESCRIPTION
**Pull request by antoniascheidel**
yay!

### CODE REVIEW

**Comment by antoniascheidel** [comment]
👍

**Comment by antoniascheidel** [comment]
:shipit:

**Comment by lownesc** [comment]
approved

**Comment by lownesc** [comment]
LGTM

**Comment by lownesc** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/antoniascheidel/meaningful-lobster/pull-request/4/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=antoniascheidel/meaningful-lobster)

**Pull request merged**
