### PR TITLE
uppercase approved and fix colons

### PR DESCRIPTION
**Pull request by antoniascheidel**
adding more keywords to the approved regex

### CODE REVIEW

**Comment by antoniascheidel** [comment]
lgtm

**Comment by antoniascheidel** [comment]
:lgtm:
:(

[Approved with PullApprove](https://pullapprove.com/antoniascheidel/meaningful-lobster/pull-request/5/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=antoniascheidel/meaningful-lobster)

**Comment by antoniascheidel** [comment]
Rejected

[Rejected with PullApprove](https://pullapprove.com/antoniascheidel/meaningful-lobster/pull-request/5/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=antoniascheidel/meaningful-lobster)

**Comment by antoniascheidel** [comment]
:LGTM: because I accidentally put colons around everything. I will now submit a patch that undoes this approval!

[Approved with PullApprove](https://pullapprove.com/antoniascheidel/meaningful-lobster/pull-request/5/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=antoniascheidel/meaningful-lobster)

**Comment by lownesc** [comment]
:+1:

**Comment by lownesc** [comment]
:shipit:

[Approved with PullApprove](https://pullapprove.com/antoniascheidel/meaningful-lobster/pull-request/5/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=antoniascheidel/meaningful-lobster)

**Comment by lownesc** [comment]
-2

**Comment by lownesc** [comment]
:+1:

**Pull request merged**
